make master branch selenium 4 compliant
browserstack/selenide-browserstack pull request #14
Opened 2022-10-31 15:03 UTC by kamal-kaur04

- Make master branch selenium 4 compliant

2022-10-31 18:50 UTC, karanshah-browserstack requested changes

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/BrowserStackTest.java
>  		Map<String, String> envCapabilities = (Map<String, String>) envs.get(environment);
Map<String, Object>

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/BrowserStackTest.java
> +			capabilities.setCapability(pair.getKey().toString(), pair.getValue());
Handling of bstack:options

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/BrowserStackTest.java
> +		Map<String, String> commonCapabilities = (Map<String, String>) config.get("capabilities");
String , Object

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/BrowserStackTest.java
> +			if ((bstackOptionsMap.get("local") != null && bstackOptionsMap.get("local").toString().equalsIgnoreCase("true")) || (capabilities.getCapability("browserstack.local") != null && capabilities.getCap
This is a sel4 sample and browserstack.local shouldn't be honoured

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/BrowserStackTest.java
> +			if ((bstackOptionsMap.get("local") != null && bstackOptionsMap.get("local").toString().equalsIgnoreCase("true")) || (capabilities.getCapability("browserstack.local") != null && capabilities.getCap
Add check for ( l == null || ! l.isRunning() )

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/resources/conf/local.conf.json
> +	"server": "hub-cloud.browserstack.com",
hub.browserstack.com

2022-10-31 18:50 UTC, karanshah-browserstack commented on src/test/resources/conf/suite.conf.json
> +      "browserName": "internet explorer"
IE could be removed from sample

2022-11-04 15:11 UTC, karanshah-browserstack approved these changes

2022-11-07 05:27 UTC, francisf approved these changes

2022-11-07 05:27 UTC, merged